import pyttsx3
import pyautogui as pi
import time
import os

engine = pyttsx3.init('sapi5')
voices = engine.getProperty('voices')
engine.setProperty('voice', voices[0].id)
engine.setProperty('rate', 200)

def speak(audio):
    engine.say(audio)
    engine.runAndWait()

def webProject():
    speak("opening sir!")
    try:
        pi.press('win')
        time.sleep(1)
        speak("opening your browser")
        pi.typewrite('Egde', 0.1)
        time.sleep(1)
        pi.press('enter')
        time.sleep(1)
        speak("typing github.com")
        pi.write('github.com', 0.1)
        time.sleep(1)
        pi.press('enter')
        time.sleep(2)
        pi.moveTo(176, 380, 0.15 )
        time.sleep(2)
        pi.click(x=176, y=380, clicks=1, interval=0, button='left' )
        time.sleep(2)
        speak("showing the main code index.html")
        pi.moveTo(259, 626, 0.15)
        time.sleep(5)
        pi.click(x=259, y=626, clicks=1, interval=0, button='left' )
        time.sleep(5)
        pi.scroll(-800, 0.15)
        time.sleep(5)
        pi.scroll(800, 0.15)
        time.sleep(2)
        pi.moveTo(1084, 186, 0.15)
        time.sleep(2)
        pi.click(x=1084, y=186, clicks=1, interval=0, button='left' )
        time.sleep(2)
        pi.moveTo(231, 789, 0.15)
        time.sleep(2)
        pi.click(x=231, y=789, clicks=1, interval=0, button='left' )
        time.sleep(3)
        speak("Opening site ")
        pi.moveTo(1354, 404, 0.15)
        time.sleep(3)
        pi.click(x=1354, y=404, clicks=1, interval=0, button='left' )
        time.sleep(6)
        pi.scroll(-500, 0.15)
        time.sleep(5)
        pi.scroll(500, 0.15)
        speak(" Terning on Dark mode")
        time.sleep(5)
        pi.moveTo(1781, 134, 0.15)
        time.sleep(3)
        pi.click(x=1781, y=134, clicks=1, interval=0, button='left' )
        time.sleep(3)
        pi.click(x=1781, y=134, clicks=1, interval=0, button='left' )
        speak(" viewing the catagory of the news")
        time.sleep(3)
        pi.moveTo(362, 127, 0.15)
        time.sleep(3)
        pi.click(x=362, y=127, clicks=1, interval=0, button='left' )
        speak("viewing the Business news")
        time.sleep(3)
        pi.moveTo(353, 230, 0.15)
        time.sleep(3)
        pi.click(x=353, y=230, clicks=1, interval=0, button='left' )
        speak("opening the login page ")
        time.sleep(3)
        pi.moveTo(1667, 124, 0.15)
        time.sleep(3)
        pi.click(x=1667, y=124, clicks=1, interval=0, button='left' )
    except Exception as e:
        print("failed to open ")
        speak("Sorry, I couldn't open")
        
        
